### PR TITLE
fix: http body no close #92

### LINKED ISSUE #92: http body未关闭
https://github.com/openGemini/opengemini-client-go/blob/49423902a3ca16ac35fa57265f70914d470a964d/opengemini/ping.go#L11-L22

http body未关闭，资源泄露，问题很严重

### PR DESCRIPTION
**Pull request by dream-kzx**
Fix #92

### CODE REVIEW

**Review by Chenxulin97 — APPROVED** [review]

**Review by xuthus5 — APPROVED** [review]

**Comment by shoothzj** [comment]
Thanks for your contribution. I have one suggestion: http code 204 does not have http body. How about this?
```go
	if resp.StatusCode != http.StatusNoContent {
		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return errors.New("read ping resp failed, error: " + err.Error())
		}
+                resp.body.close()
		return errors.New("ping error resp, code: " + resp.Status + "body: " + string(body))
	}
```

**Comment by dream-kzx** [comment]
image
204 also needs to close

**Comment by xuthus5** [comment]
> Thanks for your contribution. I have one suggestion: http code 204 does not have http body. How about this?
> 
> ```go
> 	if resp.StatusCode != http.StatusNoContent {
> 		body, err := io.ReadAll(resp.Body)
> 		if err != nil {
> 			return errors.New("read ping resp failed, error: " + err.Error())
> 		}
> +                resp.body.close()
> 		return errors.New("ping error resp, code: " + resp.Status + "body: " + string(body))
> 	}
> ```

simple code:

```go
package main

import (
	"encoding/json"
	"io"
	"net"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
)

var client = &http.Client{
	Timeout: time.Second * 3,
	Transport: &http.Transport{
		DialContext: (&net.Dialer{
			Timeout: time.Second * 3,
		}).DialContext,
	},
}

func startHttpServer() {
	r := gin.Default()
	gin.SetMode(gin.ReleaseMode)
	r.GET("/ping", func(c *gin.Context) {
		c.String(http.StatusNoContent, "")
	})
	err := r.Run(":30388")
	if err != nil {
		panic(err)
	}
}

func doRequest() {
	request, err := http.NewRequest("GET", "http://localhost:30388/ping", nil)
	if err != nil {
		panic(err)
	}
	response, err := client.Do(request)
	if err != nil {
		panic(err)
	}
	if response.Body != nil {
		panic("response body should be nil")
	}
	defer response.Body.Close()
	readAll, err := io.ReadAll(response.Body)
	if err != nil {
		panic(err)
	}
	var m = make(map[string]interface{})
	err = json.Unmarshal(readAll, &m)
	if err != nil {
		panic(err)
	}
}

func main() {
	go startHttpServer()

	time.Sleep(time.Second)

	doRequest()
}

```

**Review by shoothzj — APPROVED** [review]
Nice Catch! Thanks for your contribution and welcome to the community!

**Pull request merged**
