### PR TITLE
feat: support prometheus metrics

### PR DESCRIPTION
**Pull request by xuthus5**
**Background**
To enhance monitoring and observability, we have introduced Prometheus metrics support in the project. These metrics will help us better understand the system's performance and identify potential bottlenecks.

**New Features**
In this PR, we have added the following eight Prometheus metrics:

1. `opengemini_client_query_total` Count all queries
2. `opengemini_client_query_database_total` Count of opengemini queries and classify using database
3. `opengemini_client_query_latency` Calculate the average of the queries
4. `opengemini_client_query_database_latency` Calculate the average of the queries and classify using database
5. `opengemini_client_write_total` Count of opengemini writes
6. `opengemini_client_write_database_total` Count of opengemini writes and classify using database
7. `opengemini_client_write_latency` Calculate the average of the writes
8. `opengemini_client_write_database_latency` Calculate the average of the writes and classify using database

**Impact**
This change does not affect existing functionality; it solely adds monitoring metrics.
Ensure that the Prometheus server configuration in the deployment environment is set up to scrape these new metrics.
Prometheus dependency was introduced for this project, and the project dependency is no longer pure.

### CODE REVIEW

**Comment by Chenxulin97** [comment]
how to define the metric of writing when using auto-batch point write method？using inner batch writing request's time costing as the metric?

**Review by cyruslo — APPROVED** [review]

**Comment by xuthus5** [comment]
> how to define the metric of writing when using auto-batch point write method？using inner batch writing request's time costing as the metric?

specify a tag to distinguish between batch and single write?
whether the batch feature is enabled or not, there is always one request sent. We only need to count the time spent on this request.

**Review by shoothzj — COMMENTED** [review]
I like this PR. But `counter` is bad than total. I think we need better name.
If we have a measurement level metrics, we'd better put measurement in name.

**Comment by shoothzj** [comment]
> > how to define the metric of writing when using auto-batch point write method？using inner batch writing request's time costing as the metric?
> 
> specify a tag to distinguish between batch and single write? whether the batch feature is enabled or not, there is always one request sent. We only need to count the time spent on this request.

I agree, it seems no valuable to split them.

**Comment by xuthus5** [comment]
@shoothzj @Chenxulin97 PTAL,it can work well on my local machine.

**Review by shoothzj — COMMENTED** [review]
Overall looks good. I found one nit:
- maybe we should name variable counter instead of total?

BTW, PR description needs updates.

**Review by shoothzj — APPROVED** [review]

**Pull request merged**
